---
title: "covid vaccinations"
author: "Kotomi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

NOTE: I avoided pushing the .csv file that I used in this analysis b/c GitHub says it's too large. Will try and make the data accessible elsewhere but for now they can be downloaded from the link in the project doc


```{r}
library(dplyr)
library(tidyverse)
library(janitor)
```

```{r}
getwd()
```


```{r}
covid_vaccinations <- read.csv("data/covid_vaccinations.csv") %>% clean_names()
```

```{r}
names(covid_vaccinations)
```


Separating the date into three variables so I can sort by year. Commented out b/c running this more than once confuses R
```{r}
#covid_vaccinations <- covid_vaccinations %>% 
  #separate(date, into= c("month", "date", "year"), sep = "/") %>% 
 # mutate(year=as.factor(year))
```


```{r}
covid_vaccinations %>% 
  summarise(min_dose1_pop_pct=min(administered_dose1_pop_pct, na.rm=T))
```



```{r}
covid_vaccinations %>% 
  select(year, recip_county, recip_state, svi_ctgy, administered_dose1_pop_pct, series_complete_pop_pct, booster_doses_vax_pct) %>% 
  filter(year=="2020") %>% 
  group_by(recip_state) %>% 
  summarise(mean_dose1_pct=mean(administered_dose1_pop_pct))
```









