---
title: "BIS 15"
output: html_document
date: "2025-03-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(tidyverse)
library(janitor)
library(naniar)
library(scales)
options(scipen=999)
library(lubridate)
```

```{r pressure, echo=FALSE}
COVID_vaccines <- read.csv("/Users/sanch/Desktop/National_Immunization_Survey_Adult_COVID_Module__NIS-ACM___Vaccination_Status_and_Intent_by_Demographics copy.csv")
```

```{r}
COVID_vaccines_new <- COVID_vaccines%>%
   mutate(Geography = ifelse(Geography %in% c("NY-Rest of State", "NY-City of New York"), 
                            "New York", Geography)) 
```

```{r}
COVID_vaccines_new %>% 
  group_by(Geography) %>% 
  filter(Geography %in% c("California", "Texas", "New York", "Florida", "Pennsylvania")) %>% 
  filter(Indicator.Category == "Probably or Definitely Will Not Get Vaccinated") %>% 
  filter(Geography != "National") %>% 
  summarise(total_sample_size = sum(Sample.Size)) %>% 
  ggplot(aes(x = reorder(Geography, total_sample_size), y = total_sample_size, fill = Geography)) +
  geom_col() +
  labs(title = "COVID-19 Non-Vaccinated Population by State", x = "State", y = "Number of People Not Vaccinated") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  scale_fill_brewer(palette = "Paired")  # Apply the "Paired" color palette
```

```{r}
COVID_vaccines_new %>% 
  group_by(Geography) %>% 
  filter(Indicator.Category == "Definitely will get an updated bivalent booster (among adults who completed primary series)" | 
           Indicator.Category == "Vaccinated (>=1 dose)" | 
           Indicator.Category == "Received updated bivalent booster dose (among adults who completed primary series)") %>% 
  filter(Geography %in% c("California", "Texas", "New York", "Florida", "Pennsylvania")) %>% 
  filter(Geography != "National") %>% 
  summarise(total_sample_size = sum(Sample.Size)) %>%  
  arrange(-total_sample_size) %>% 
  top_n(10, total_sample_size) %>% 
  ggplot(aes(x = reorder(Geography, total_sample_size), y = total_sample_size, fill = Geography)) +
  geom_col() +
  
  labs(title = "COVID-19 Vaccinated Population by State", x = "State", y = "Number of People Vaccinated") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  scale_fill_brewer(palette = "Paired")  # Apply the "Paired" color palette

```

```{r}
COVID_vaccines_clean <- COVID_vaccines_new %>% 
  separate(Time.Period, into = c("Start", "End"), sep = " -") %>%
  
  # Step 2: Separate Start into Start_Month and Start_Day
  separate(Start, into = c("Start_Month", "Start_Day"), sep = " ") %>%
  
  # Step 3: Separate End into End_Month and End_Day
  mutate(End = str_trim(End)) %>% 
  separate(End, into = c("End_Month", "End_Day"), sep = " ")
```

```{r}
COVID_vaccines_new <- COVID_vaccines_new %>%
   separate(Time.Period, into = c("start_date", "end_date"), sep = " - ")

```

```{r}
library(dplyr)
library(ggplot2)
library(lubridate)

COVID_vaccines_new %>%
  filter(
           Indicator.Category == "Vaccinated (>=1 dose)" |
           Indicator.Category == "Received updated bivalent booster dose (among adults who completed primary series)") %>% 
  filter(Geography %in% c("California", "Texas", "New York", "Florida", "Pennsylvania")) %>% 
  filter(Geography != "National") %>%
  # Combine 'start_date' and 'Year' to create a proper Date column
  mutate(start_date = paste(start_date, Year), 
         start_date = mdy(start_date)) %>%  # Convert to Date using 'lubridate'
  group_by(start_date, Geography) %>%  # Group by both start_date and Geography
  summarise(Sample.Size = sum(Sample.Size)) %>%  # Summing Sample.Size for each date and geography
  ggplot(aes(x = start_date, y = Sample.Size, color = Geography)) +  # Map Geography to color
  geom_line() +
  labs(title = "Total COVID-19 Vaccinated Population Over Time by State",
       x = "Date", y = "Sample Size") +
  theme_minimal() +
  scale_x_date(date_labels = "%b %Y", date_breaks = "1 month") +  # Format the x-axis to show month and year
  scale_color_brewer(palette = "Paired") +  # Apply the "Paired" color palette
  theme(legend.position = "bottom", 
        axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels to prevent crowding

```
```{r}
library(dplyr)
library(ggplot2)
library(lubridate)

COVID_vaccines_new %>%
  filter(Indicator.Category=="Probably or Definitely Will Not Get Vaccinated") %>% 
  filter(Geography %in% c("California", "Texas", "New York", "Florida", "Pennsylvania")) %>% 
  filter(Geography != "National") %>%
  # Combine 'start_date' and 'Year' to create a proper Date column
  mutate(start_date = paste(start_date, Year), 
         start_date = mdy(start_date)) %>%  # Convert to Date using 'lubridate'
  group_by(start_date, Geography) %>%  # Group by both start_date and Geography
  summarise(Sample.Size = sum(Sample.Size)) %>%  # Summing Sample.Size for each date and geography
  ggplot(aes(x = start_date, y = Sample.Size, color = Geography)) +  # Map Geography to color
  geom_line() +
  labs(title = "COVID-19 Non-Vaccinated Population Over Time by State",
       x = "Date", y = "Sample Size") +
  theme_minimal() +
  scale_x_date(date_labels = "%b %Y", date_breaks = "1 month") +  # Format the x-axis to show month and year
  scale_color_brewer(palette = "Paired") +  # Apply the "Paired" color palette
  theme(legend.position = "bottom", 
        axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels to prevent crowding
```
```{r}
COVID_vaccines_new %>%
  filter(Indicator.Category == "Definitely will get an updated bivalent booster (among adults who completed primary series)" |
           Indicator.Category == "Vaccinated (>=1 dose)" |
           Indicator.Category == "Received updated bivalent booster dose (among adults who completed primary series)") %>% 
 
  filter(Geography == "National") %>%
  # Combine 'start_date' and 'Year' to create a proper Date column
  mutate(start_date = paste(start_date, Year), 
         start_date = mdy(start_date)) %>%  # Convert to Date using 'lubridate'
  group_by(start_date) %>%  # Group by both start_date and Geography
  summarise(Sample.Size = sum(Sample.Size)) %>%  # Summing Sample.Size for each date and geography
  ggplot(aes(x = start_date, y = Sample.Size)) +  # Map Geography to color
  geom_line() +
  labs(title = "Total COVID-19 Vaccinated Population in the U.S (2021-2023)",
       x = "Date", y = "Sample Size") +
  theme_minimal() +
  scale_x_date(date_labels = "%b %Y", date_breaks = "1 month") +  # Format the x-axis to show month and year
  theme(legend.position = "bottom", 
        axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
COVID_vaccines_new %>%
  group_by(Indicator.Category) %>% 
  filter(Indicator.Category == "Definitely will get an updated bivalent booster (among adults who completed primary series)" |
           Indicator.Category == "Vaccinated (>=1 dose)" |
           Indicator.Category == "Received updated bivalent booster dose (among adults who completed primary series)") %>% 
 
  filter(Geography == "National") %>%
  # Combine 'start_date' and 'Year' to create a proper Date column
  mutate(start_date = paste(start_date, Year), 
         start_date = mdy(start_date)) %>%  # Convert to Date using 'lubridate'
  group_by(start_date) %>%  # Group by both start_date and Geography
  summarise(Sample.Size = sum(Sample.Size)) %>%  # Summing Sample.Size for each date and geography
  ggplot(aes(x = start_date, y = Sample.Size)) +  # Map Geography to color
  geom_line() +
  labs(title = "Total COVID-19 Vaccinated Population in the U.S (2021-2023)",
       x = "Date", y = "Sample Size") +
  theme_minimal() +
  scale_x_date(date_labels = "%b %Y", date_breaks = "1 month") +  # Format the x-axis to show month and year
  theme(legend.position = "bottom", 
        axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
library(ggplot2)
library(dplyr)
library(lubridate)

COVID_vaccines_new %>%
  filter(Indicator.Category %in% c("Vaccinated (>=1 dose)", 
                                   "Received updated bivalent booster dose (among adults who completed primary series)")) %>%
  filter(Geography == "National") %>%
  group_by(Indicator.Category, start_date, Year) %>%
  summarise(Sample.Size = sum(Sample.Size), .groups = "drop") %>%
  mutate(start_date = paste(start_date, Year),
         start_date = mdy(start_date)) %>%
  ggplot(aes(x = start_date, y = Sample.Size, color = Indicator.Category)) + 
  geom_line(size = 1.2) +  # Adjust line thickness for better visibility
  scale_color_brewer(palette = "Paired") +  # Use Paired color palette
  labs(title = "Trends in COVID-19 Vaccination and Booster Shots in the U.S. (2021-2023)",
       x = "Date", y = "Population Size",
       color = "Vaccination Category") +
  theme_minimal() +
  scale_x_date(date_labels = "%b %Y", date_breaks = "1 month") +
  theme(legend.position = "bottom", 
        legend.text = element_text(size = 7),  # Reduce legend text size
        legend.title = element_text(size = 9),  # Reduce legend title size
        axis.text.x = element_text(angle = 45, hjust = 1))

```


```{r}


filtered_table <- COVID_vaccines %>%
  filter(Indicator.Category %in% c(
    "Received updated bivalent booster dose (among adults who completed primary series)",
    "Vaccinated (>=1 dose)"
   
  )) %>%
  count(Indicator.Category)

print(filtered_table)

```

```{r}
COVID_vaccines_new %>%
  filter(
           Indicator.Category == "Received updated bivalent booster dose (among adults who completed primary series)") %>% 
  filter(Geography %in% c("California", "Texas", "New York", "Florida", "Pennsylvania")) %>% 
  filter(Geography != "National") %>%
  # Combine 'start_date' and 'Year' to create a proper Date column
  mutate(start_date = paste(start_date, Year), 
         start_date = mdy(start_date)) %>%  # Convert to Date using 'lubridate'
  group_by(start_date, Geography) %>%  # Group by both start_date and Geography
  summarise(Sample.Size = sum(Sample.Size)) %>%  # Summing Sample.Size for each date and geography
  ggplot(aes(x = start_date, y = Sample.Size, color = Geography)) +  # Map Geography to color
  geom_line() +
  labs(title = "COVID-19 Booster-dose Vaccinated Population Over Time by State",
       x = "Date", y = "Sample Size") +
  theme_minimal() +
  scale_x_date(date_labels = "%b %Y", date_breaks = "1 month") +  # Format the x-axis to show month and year
  scale_color_brewer(palette = "Paired") +  # Apply the "Paired" color palette
  theme(legend.position = "bottom", 
        axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels to prevent crowding

```





